name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.SERVER_IP }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << 'EOF'
            cd fastapi-book-project
            echo "Current directory: $(pwd)"
            echo "Git remote configuration"
            git remote -v fd
            echo "Pull from main branch"
            git fetch origin
            echo "Pull from main"
            git pull origin main || { echo "git pull failed"; exit 1; }
            echo "Install requirements"
            source venv/bin/activate
            pip install -r requirements.txt
            echo "Return Service"
            sudo systemctl daemon-reload
            echo "Restart FastAppi service"
            sudo systemctl restart fastapp.service
            echo "Restart Nginx"
            sudo systemctl restart nginx
          EOF