name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST_VALUE }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deployment starting..."
            # Navigate to project directory (ensure this directory exists on your EC2 instance)
            cd hngx-stage2-fastapi-book-project || exit 1

            # Update the repository
            git fetch --all
            git pull origin main

            # Set up the virtual environment and install dependencies
            python3 -m venv venv || exit 1
            source venv/bin/activate || exit 1
            python -m pip install --upgrade pip || exit 1
            pip install -r requirements.txt || exit 1

            # Stop any existing uvicorn process
            echo "Stopping existing application..."
            killall uvicorn || echo "No existing process found"
            echo "Application stopped successfully"

            # Start the FastAPI application using uvicorn
            echo "Starting application..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
            echo "Application started successfully"
